name: Build static ffmpeg

on:
  push:
  pull_request:

jobs:
  package-linux:
    runs-on: self-hosted
    strategy:
      matrix:
        arch:
          - x86_64
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo yum update -y && \
          sudo yum install -y subversion yasm nasm wget
      - name: Install ARM64 compiler
        if: env.ARCH == 'arm64'
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build
        run: ./build-linux.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-linux-${{ env.ARCH }}
          path: artifacts/

  package-windows:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - x86_64
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y yasm mingw-w64 subversion libz-mingw-w64-dev
      - name: Build
        run: ./build-windows.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-windows-${{ env.ARCH }}
          path: artifacts/

  package-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        # https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary#Update-the-Architecture-List-of-Custom-Makefiles
        target:
          - x86_64-apple-macos10.9
          - arm64-apple-macos11
    env:
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install yasm nasm subversion
      - name: Build
        run: ./build-macos.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-${{ matrix.target }}
          path: artifacts/

  release:
    runs-on: self-hosted
    needs:
      - package-linux
      - package-windows
      - package-macos
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Make tarballs
        run: |
          mkdir artifacts/release/
          cd artifacts/
          for dir in ffmpeg-*/ffmpeg-*
          do
            name=$(basename $dir)
            tar czf release/$name.tar.gz -C $(dirname $dir) $name
          done
      
          mkdir apps
          mkdir apps/win_x86_64
          mkdir apps/mac_x86_64
          mkdir apps/mac_arm64
          mkdir apps/linux_x86_64

          cp ./ffmpeg-windows-x86_64/ffmpeg-5.1.2-audio-x86_64-win/bin/ff* apps/win_x86_64/
          cp ./ffmpeg-arm64-apple-macos11/ffmpeg-5.1.2-audio-arm64-apple-macos11/bin/ff* apps/mac_arm64/
          cp ./ffmpeg-x86_64-apple-macos10.9/ffmpeg-5.1.2-audio-x86_64-apple-macos10.9/bin/ff* apps/mac_x86_64/
          cp ./ffmpeg-linux-x86_64/ffmpeg-5.1.2-audio-x86_64-linux-gnu/bin/ff* apps/linux_x86_64
   
      # upload this so it is available to download in action artifacts.    
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: apps
          path: artifacts/apps

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: artifacts/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
